masculine = {
'dominant': '',
'boast': 'provide',
'boasts': 'provides',
'lead': 'coordinate',
'competition': '',
'compete': '',
'strong': 'excellent',
'determined': 'committed',
'influencing': '',
'influence': '',
'perform': '',
'individual': '',
'individually': '',
'competitive': 'excellent',
'superior': 'top quality',
'satisfy': '',
'manage': '',
'direct': '',
'progress': '',
'ensure': '',
'accurate': '',
'control': '',
'determine': 'establish',
'proud': '',
'impressive': '',
'success': '',
'self-reliant': 'compassionate',
'demonstrated': '',
'demonstrate': '',
'independent': 'capable of working with minimal supervision',
'independently': 'with minimal supervision',
'analyze': 'understand',
'ability': '',
'maintain': '',
'logically': '',
'troubleshoot': '',
'deliver': '',
'ambition': 'hope',
'challenge': 'motivate',
'boss': 'head',
'leadership': 'interpersonal skills',
'leader': 'role model',
'superior': 'ideal',
'self-confident': 'pleasant',
'decisive': 'responsible',
'decisively': 'responsibly',
'detail-oriented': 'attentive to detail',
'recruit': 'connect',
'negotiate': 'sensitively negotiate',
'principled': 'caring',
'dedicated': 'passionate',
'dedication': 'passion',
'able': 'willing',
'administer': 'provide',
'aware': 'sensitive',
'interface': 'connect',
'control': 'coordinate',
'manage': 'coordinate',
'he': 'they',
'him': 'them',
'his':'their',
}

feminine = {
'community': '',
'commit': '',
'committed': 'determined',
'understand': 'analyze',
'understanding': 'analyzing',
'proficient': 'strong',
'collaborate': 'perform',
'collaborates': 'performs',
'collaborative': 'performance-oriented',
'team': '',
'sensitive': 'logical',
'help': '',
'dependable': 'self-reliant',
'loyal': '',
'honest': 'logical',
'personal': '',
'interpret': 'analyze',
'service': '',
'respond': '',
'innovative': 'logical',
'provide': 'deliver',
'hope': 'ambition',
'pleasant': 'competitive',
'nurture': 'challenge',
'support': '',
'flexible': 'variable',
'cheerful': '',
'capable': 'independent',
'motivate': 'challenge',
'head': 'leader',
'career development': 'career advancement',
'interpersonal': 'leadership',
'role model': 'leader',
'develop': 'facilitate',
'ideal': 'superior',
'attentive': 'detail-oriented',
'connect': '',
'serve': 'negotiate',
'serves': 'negotiates',
'consider': 'analyze',
'caring': '',
'compassionate': 'principled',
'passion': 'interest',
'passionate': 'interested',
'devoted': 'hard-working',
'polite': 'civil',
'coordinate': 'control',
}
